name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  

      #- name: Install Fantomas (Code Formatter)
       # run: dotnet tool install --create-manifest-if-needed -g Fantomas --version 5.1.0 --no-cache

#      - name: Format code with Fantomas (HashSet)
 #       run: fantomas fplab2/src/HashSet.fs
#
 #     - name: Format code with Fantomas (Test)
  #      run: fantomas fplab2/test/Program.fs
        
      - name: Run test (HashSet)
        run: cd fplab2 && dotnet test

    
